### ISSUE TITLE
Parameter matching incompatible with T-SQL geography types

### ISSUE THREAD

**Issue by jezza323** [TrevorPilley/MicroLite#400] opened 2015-07-19 04:01 UTC
I am trying to implement a query using T-SQL geography types, and I get a param count mismatch issue. Looking at the code it seems to match on : or @ chars but the : char is required for geography types - eg - "SELECT *, location.STDistance(geography::Point(@p0, @p1, 4326)) as distance..."

This appears to result in extra params being detected. I will take a closer look soon, I am guessing its picking up ":Point" as a named parameter.

Any suggestions for a work around would be appreciated in the meantime.

**Comment by TrevorPilley** [comment] 2015-07-19 14:00
It sounds like that's the case, there isn't really a work around that I can think of, I'll try and get a fix sorted in the next day or two unless you are able to send a patch?

**Comment by jezza323** [comment] 2015-07-20 00:47
Provided beither :: or @@ are valid for params i can do a PR later this week. Just under some time pressure at the moment

-------- Original message --------

**Comment by TrevorPilley** [comment] 2015-07-20 07:53
Looking at it, it should already ignore `::` using the same logic it uses to ignore '@@' - https://github.com/TrevorPilley/MicroLite/blob/develop/MicroLite/SqlUtility.cs#L158

Can you provide a sample SQL query which we can use to create a failing test?

**Comment by jezza323** [comment] 2015-07-22 12:18
Looking at this a bit more closely at the moment. Looks like you are right and its not the :: chars

Using 

                        sites = session.Paged<SiteWithDistance>(query, PagingOptions.ForPage(page, pageSize));

The following SQL fails for me, with the reported error - "The number of parameters in the SQL statement and the number of specified parameter arguments should match. However '4' parameters used in the SQL statement and '6' parameter arguments were specified."

![image](https://cloud.githubusercontent.com/assets/8828643/8825015/c30b75e0-30be-11e5-85e7-cf8f912ff456.png)

Sql for copy and paste ease is 

SELECT *, @p0 AS Distance, @p1 AS Test, 0 AS SearchIndex FROM ref_site ORDER BY SearchIndex, omi_site_name

As you can see in the image 2 SqlArguments are defined, both decimal types with value 1. I have tried varying the values, but doesn't seem to make a difference.

The following run in SSMS executes successfully

DECLARE @p0 DECIMAL = 1
DECLARE @p1 DECIMAL = 1
SELECT *, @p0 AS Distance, @p1 AS Test, 0 AS SearchIndex FROM ref_site ORDER BY SearchIndex, omi_site_name

**Comment by TrevorPilley** [comment] 2015-07-24 08:28
Which version of SQL Server are you using?

**Comment by jezza323** [comment] 2015-07-24 08:53
Sql Server 2014. I will be able to debug against the microlite code tonight, so I will have more info or a PR then


Sent from my Samsung device

-------- Original message --------

**Comment by TrevorPilley** [comment] 2015-07-24 08:57
OK so you're using `ForMsSql2012Connection`?

**Comment by jezza323** [comment] 2015-07-24 10:06
Yes I am, debugging now!

**Comment by TrevorPilley** [comment] 2015-07-24 10:11
I think I've found the issue! when we do a paged call, we do a count as well as getting the paged set which us shown on the `PagedResult<T>` class.

The count query and paged query are combined into a single query when we go to the database server - the problem is with the logic in the `DbDriver.CountQuery` method.

Here's what's happening:

1. You do `session.Paged(new SqlQuery("SELECT *, @p0 AS Distance, @p1 AS Test, 0 AS SearchIndex FROM ref_site ORDER BY SearchIndex, omi_site_name", 1m, 1m), PagingOptions.ForPage(1, 1))`
2. MicroLite generates a select count which ends up as `new SqlQuery("SELECT COUNT(*) FROM ref_site", 1m, 1m)`
3. MicroLite generates a paged query which ends up as `new SqlQuery("SELECT *, @p0 AS Distance, @p1 AS Test, 0 AS SearchIndex FROM ref_site ORDER BY SearchIndex, omi_site_name OFFSET @p2 ROWS FETCH NEXT @p3 ROWS ONLY", 1m, 1m, 1, 1)`
4. MicroLite combines the select count query and paged query as `new SqlQuery("SELECT COUNT(*) FROM ref_site;
SELECT *, @p2 AS Distance, @p3 AS Test, 0 AS SearchIndex FROM ref_site ORDER BY SearchIndex, omi_site_name OFFSET @p4 ROWS FETCH NEXT @p5 ROWS ONLY", 1m, 1m, 1m, 1m, 1, 1)`

Notice that the combined has @p2, @p3, @p4, @p5 instead of @p0, @p2, @p3, @p4 and that there are 6 args (1m, 1m, 1m, 1m, 1, 1) - that's the problem.

It's occurring because the count is copying the arguments but there is where condition so they end up in the combined query twice.

So to fix it, `SqlDialect.CountQuery` shouldn't copy the arguments array if there is no where clause.

**Comment by jezza323** [comment] 2015-07-24 10:20
That does seem to be the problem. Adding a WHERE @p0 = @p0 AND @p1 = @p1 works around the issue

**Comment by TrevorPilley** [comment] 2015-07-24 10:39
Yeah that's a hacky work around but it should get it working until the method is improved.

Based upon that sample query, I'm not seeing anything to do with geography types - is there still something that needs fixing around those?

**Comment by jezza323** [comment] 2015-07-24 11:18
The geography query was presenting the same bug as the simplified query. Using the work around I have geography type working. Sorry, I jumped the gun while I didnt have time to debug properly!

I am just writing some tests now for a PR

**Comment by jezza323** [comment] 2015-07-24 11:35
PR submitted, sorry im not sure how to link to the issue in Github

**Comment by TrevorPilley** [comment] 2015-07-24 22:30
Thanks, I'll take a look over the weekend

**Comment by TrevorPilley** [comment] 2015-07-26 10:11
Closed by 0a8e763

**Comment by TrevorPilley** [comment] 2015-07-26 14:29
Fixed in MicroLite 6.2.4 which has just been released to NuGet

**Comment by bityardigans** [comment] 2016-05-21 20:36
FYI, this appears to be broken in 6.2.9 - every initial call fails with the error mentioned above but every subsequent call works fine:

`
        public async Task<PagedResult<T>> FindAsync<T>(SqlQuery query, 
            int offset = 0, int limit = 0) where T : class, IEntity, new()
        {
            using (IAsyncSession session = this.Factory.OpenAsyncSession())
            {
                return await session
                .PagedAsync<T>(query, PagingOptions.SkipTake((offset > 0) ? offset : 0, (limit > 0) ? limit : 100));
            }
        }
`

any ideas?

**Comment by TrevorPilley** [comment] 2016-05-21 20:43
Can you show an example Sql query?

**Comment by bityardigans** [comment] 2016-05-21 20:52
Generated query looks and runs fine in SSMS - SELECT [CreatedBy],[CreatedDate],[Email],[FirstName],[IsActive],[LastName],[UpdatedBy],[UpdatedDate],[UserId],[Username] FROM [User] WHERE ((Username = @p0))

Inspecting the SqlQuery instance passed into the PagedAsync method shows 1 argument being passed forward (as expected). Somewhere in the internals it is appending the additional params and it looks to be the exact issue above (same error) but only on the very first run which is weird.

Using ForMsSql2012Connection w/ the fluent config if that helps...

**Comment by TrevorPilley** [comment] 2016-05-22 10:29
I can't reproduce what you're saying using the following:

```
public interface IEntity { }

public class User : IEntity
{
    public string CreatedBy {  get; set; }
    public DateTime CreatedDate {  get; set; }
    public string Email {  get; set; }
    public string FirstName {  get; set; }
    public bool IsActive {  get; set; }
    public string LastName {  get; set; }
    public string UpdatedBy {  get; set; }
    public DateTime UpdatedDate {  get; set; }
    public int UserId {  get; set; }
    public string Username {  get; set; }
}

FindAsync<User>(new SqlQuery("SELECT [CreatedBy],[CreatedDate],[Email],[FirstName],[IsActive],[LastName],[UpdatedBy],[UpdatedDate],[UserId],[Username] FROM [User] WHERE ((Username = @p0))", "JoeBloggs"))
```

Original Query provided to FindAsync:
```
SELECT [CreatedBy],[CreatedDate],[Email],[FirstName],[IsActive],[LastName],[UpdatedBy],[UpdatedDate],[UserId],[Username] FROM [User] WHERE ((Username = @p0))
@p0 = JoeBloggs
```

The Count Query generated by MicroLite:
```
SELECT COUNT(*) FROM [User] WHERE ((Username = @p0))
@p0 = JoeBloggs
```

The Original Query as Paged by MicroLite:
```
SELECT [CreatedBy],[CreatedDate],[Email],[FirstName],[IsActive],[LastName],[UpdatedBy],[UpdatedDate],[UserId],[Username] FROM [User] WHERE ((Username = @p0)) ORDER BY CURRENT_TIMESTAMP OFFSET @p1 ROWS FETCH NEXT @p2 ROWS ONLY
@p0 = JoeBloggs
@p1 = 0
@p2 = 100
```

The Combined Query - This is what is actually sent to the database:
```
SELECT COUNT(*) FROM [User] WHERE ((Username = @p0));
SELECT [CreatedBy],[CreatedDate],[Email],[FirstName],[IsActive],[LastName],[UpdatedBy],[UpdatedDate],[UserId],[Username] FROM [User] WHERE ((Username = @p1)) ORDER BY CURRENT_TIMESTAMP OFFSET @p2 ROWS FETCH NEXT @p3 ROWS ONLY
@p0 = JoeBloggs
@p1 = JoeBloggs
@p2 = 0
@p3 = 100
```

Are you able to explain any further what problem you are seeing?

**Comment by TrevorPilley** [comment] 2016-06-17 08:59
Any updates @bityardigans?

**Closed** 2016-06-29 09:17 UTC

**Comment by bityardigans** [comment] 2016-06-29 10:50
Sorry, meant to close this. It went away with the latest version of the microlite webapi extensions. Seemed to be happening w odata queries specifically.

Thanks-
